INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home & Garden', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Toys & Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sports & Outdoors', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Health & Beauty', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Food & Grocery', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Beauty & Personal Care', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Industrial & Scientific', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Office Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tools & Home Improvement', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Grocery & Gourmet Food', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cell Phones & Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Arts, Crafts & Sewing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Software', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Camera & Photo', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Appliances', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home Improvement', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Baby', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sports', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Health', NOW());
